services:
  backend:
    build: .
    ports:
      - "8000:8000"

  db:
    container_name: postgresql_db
    image:  postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}