[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Johann Hemmann <johann.hemmann@code.berlin>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.1"
fastapi = "^0.68.0"
requests = "^2.26.0"
websockets = "^9.1"
wsproto = "^1.0.0"
uvicorn = {extras = ["standart"], version = "^0.15.0"}

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
