[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Johann Hemmann <johann.hemmann@code.berlin>"]
readme = "README.md"

[tool.poetry.dependencies]
click = "^8.0.1"
fastapi = "^0.65.2"
python = "^3.9"
requests = "^2.25.1"
uvicorn = {extras = ["standard"], version = "^0.14.0"}

[tool.poetry.dev-dependencies]
black = "^21.5-beta.2"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
