[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Johann Hemmann <johann.hemmann@code.berlin>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.4"
requests = "^2.25.1"
psycopg2-binary = "^2.8.6"

[tool.poetry.dev-dependencies]
black = "^21.5-beta.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
