branch-defaults:
  main:
    environment: Face-The-Facts-Backend-Main
environment-defaults:
  Face-The-Facts-Backend-Main:
    branch: null
    repository: null
global:
  application_name: Face-The-Facts Backend
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
