politician_route_standard = {
    "id": 78973,
    "label": "Karin Strenz",
    "party": {
        "id": 2,
        "label": "CDU",
        "party_style": {
            "id": 2,
            "display_name": "CDU",
            "foreground_color": "#FFFFFF",
            "background_color": "#636363",
            "border_color": None,
        },
    },
    "occupations": ["MdB"],
    "sidejobs": [
        {
            "id": 6893,
            "entity_type": "sidejob",
            "label": "Vorsitzende",
            "income_level": None,
            "interval": None,
            "created": "2018-04-16",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 4541,
            "entity_type": "sidejob",
            "label": "Stellv. Vorsitzende, ehrenamtlich",
            "income_level": None,
            "interval": None,
            "created": "2017-09-23",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 413,
            "entity_type": "sidejob",
            "label": "Beteiligung (bis 31.12.2014)",
            "income_level": None,
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 872,
                "entity_type": "sidejob_organization",
                "label": "Karin Strenz GbR",
            },
        },
        {
            "id": 412,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
        {
            "id": 411,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
    ],
    "cvs": [
        {
            "id": 633,
            "short_description": "Geboren am 14. Oktober 1967 in Lübz; evangelisch-lutherisch; verheiratet.",
            "raw_text": "Besuch der Polytechnischen Oberschule Lübz; Studium am Institut für Lehrerbildung in Rostock; Studium an der Pädagogischen Hochschule in Magdeburg; Abschluss als Diplom-Lehrerin für Sonderschulen; Zusatzstudium der Erziehungswissenschaften an der Goethe-Universität Frankfurt/Main. Lehrerin an der Sonderschule in Wanzleben bei Magdeburg; 1992 bis 2002 Angestellte einer Import- und Großhandelsfirma in Frankfurt/Main. Seit 2015 Vorsitzende der Deutsch-Kasachischen-Gesellschaft e. V. Seit 2001 Vorsitzende des CDU-Kreisverbandes Parchim; 1999 bis 2005 Mitglied des CDU-Landesvorstandes; 2001 bis 2005 Stellvertretende CDU-Landesvorsitzende; Mitglied der Christlich-Demokratische Arbeitnehmerschaft (CDA); seit 2013 Ehrenvorsitzende CDU-Kreisverband Ludwigslust-Parchim. Seit 1999 Mitglied des Kreistages zu Parchim; seit 2001 Vorsitzende der CDU-Kreistagsfraktion Parchim; seit 2002 Mitglied des Landtages von Mecklenburg-Vorpommern; Ausschüsse: Wirtschaft, Arbeit, Bau und Landesentwicklung, Petitionsausschuss; 2002 bis 2006 arbeitsmarktpolitische Sprecherin der CDU-Fraktion; seit November 2007 verantwortlich für das Sorgentelefon der CDU-Fraktion; 2006 bis 2008 Aufsichtsratsvorsitzende des Flughafens Parchim. Mitglied des Deutschen Bundestages seit Oktober 2009. Karin Strenz ist am 21. März 2021 verstorben, Nachfolgerin ist die Abgeordnete Maika Friemann-Jennert, CDU/CSU. ** verstorben ",
            "politician_id": 78973,
        }
    ],
    "abgeordnetenwatch_url": "https://www.abgeordnetenwatch.de/profile/karin-strenz",
    "weblinks": [
        {
            "link": "https://www.wahl.de/politiker/cdu/karin-strenz",
            "id": 44558,
            "politician_id": 78973,
        },
        {"link": "http://www.strenz.de/", "id": 44559, "politician_id": 78973},
        {
            "link": "https://www.wen-waehlen.de/btw09/kandidaten/karin-strenz_10058.html",
            "id": 44560,
            "politician_id": 78973,
        },
        {
            "link": "https://de.wikipedia.org/wiki/Karin_Strenz",
            "id": 44561,
            "politician_id": 78973,
        },
        {
            "link": "https://www.facebook.com/Karin.Strenz",
            "id": 44562,
            "politician_id": 78973,
        },
    ],
    "votes_and_polls": [
        {
            "Vote": {
                "id": 382871,
                "entity_type": "vote",
                "label": "Karin Strenz - Internetportal Indymedia verbieten",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/382871",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 4018,
                "vote": "no",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 4018,
                "label": "Internetportal Indymedia verbieten",
                "field_intro": '<p>Mit ihrem Antrag fordert die AfD-Fraktion das Verbot des Internetportals <em>indymedia</em>. Laut AfD stelle der Verein eine "Bedrohung der öffentlichen Ordnung durch gewaltbereite Linksextremisten" dar.</p>\r\n\r\n<p>Alle Mitglieder der Fraktionen CDU/CSU, SPD, Grüne. Linke und FDP stimmten ausnahmslos für die Beschlussempfehlung des Ausschusses für Inneres und Heimat und somit gegen den Antrag der AfD.</p>\r\n',
                "field_poll_date": "2021-02-25",
                "poll_passed": False,
            },
        },
        {
            "Vote": {
                "id": 373238,
                "entity_type": "vote",
                "label": "Karin Strenz - Weiterführung des Bundeswehreinsatzes im Irak",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/373238",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3948,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3948,
                "label": "Weiterführung des Bundeswehreinsatzes im Irak",
                "field_intro": '<p>Mit dem Weiterführen des bereits laufenden Bundeswehreinsatzes im Irak soll das erneute Erstarken des islamischen Staates verhindert und die Versöhnung der Konfliktparteien Irak und Syrien gefördert werden.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD sowie die Fraktion der FDP stimmten der <a href="https://dip21.bundestag.de/dip21/btd/19/232/1923212.pdf">Beschlussempfehlung</a> des Auswärtigen Ausschusses zu. Der Antrag der Bundesregierung wurde somit angenommen. Die Fraktionen Bündnis 90/DieGrünen, Die LINKE und die AfD stimmten einstimmig gegen den Einsatz. Auch neun SPD-Fraktionsmitglieder, darunter <a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/dirk-heidenblut">Dirk Heidenblut</a> und&nbsp;<a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/cansel-kiziltepe">Cansel Kiziltepe</a> stellten sich gegen den den <a href="https://dip21.bundestag.de/dip21/btd/19/222/1922207.pdf">Antrag</a>. Ebenso <a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/wieland-schinnenburg">Dr. Wieland Schinnenburg</a> als einziges Mitglied der Fraktion FDP.</p>\r\n\r\n<p>&nbsp;</p>\r\n',
                "field_poll_date": "2020-10-29",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 366526,
                "entity_type": "vote",
                "label": "Karin Strenz - Nachtragshaushalt 2020: Corona Konjunktur- und Krisenbewältigungspaket",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/366526",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3749,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3749,
                "label": "Nachtragshaushalt 2020: Corona Konjunktur- und Krisenbewältigungspaket",
                "field_intro": '<p>Mit dem <a href="http://dip21.bundestag.de/dip21/btd/19/200/1920000.pdf">Gesetzesentwurf </a>fordern die Regierungsfraktionen CDU/CSU und SPD die nachträgliche Erhöhung des Haushaltes für das Jahr 2020 auf 509,3 Milliarden Euro (<a href="https://www.abgeordnetenwatch.de/bundestag/19/abstimmungen/bundeshaushalt-2020">vorher 362 Milliarden Euro</a>) von der Bundesregierung. Mit dem Paket sollen die negativen Auswirkungen auf Wirtschaft und Gesellschaft abgefedert werden.</p>\r\n\r\n<p>Die Regierungsfraktionen stimmten geschlossen <strong>für </strong>den zweiten Nachtragshaushalt. <strong>Gegen </strong>den Antrag votierte die FDP- und AfD-Fraktion. Die Grünen- und Linksfraktion <strong>enthielt </strong>sich zum größten Teil ihrer Stimme. Damit wurde der zweite Nachtragshaushalt für das Jahr 2020 <strong>angenommen</strong>.</p>\r\n',
                "field_poll_date": "2020-07-02",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 365258,
                "entity_type": "vote",
                "label": "Karin Strenz - Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/365258",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3714,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3714,
                "label": "Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "field_intro": '<p>Der <a href="https://dip21.bundestag.de/dip21/btd/19/193/1919371.pdf">Gesetzesentwurf </a>der Bundesregierung will die EU-Richtlinie des EU-Parlamentes zur Stärkung der Rechte von Arbeitnehmer:innen aus dem EU-Ausland umsetzen. Mit der Richtlinie sollen unter anderem aus dem EU-Ausland entsandte Arbeitnehmer:innen nicht mehr nur den Anspruch auf den Mindestlohn, sondern auch auf den Tariflohn aus allgemeinverbindlichen Tarifverträgen haben.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten ebenso wie die Grünenfraktion für den Antrag. Dieser wurde damit angenommen. Die AfD stimmte, genau wie die FDP-Fraktion gegen den Antrag. Die Linken-Abgeordneten enthielten sich ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-06-18",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 363840,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/363840",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3710,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3710,
                "label": "Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr am maritimen Teil der friedenssichernden Mission "United Nations Interim Force in Lebanon" (<a href="https://www.bundeswehr.de/de/einsaetze-bundeswehr/die-bundeswehr-im-libanon">UNIFIL</a>) verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an der Überwachung der Seegrenzen des Libanon.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die FDP und die Grünen. Damit wurde der Antrag angenommen. Die AfD-Fraktion und Linke votierten geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 364549,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/364549",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3711,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3711,
                "label": "Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919001.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr an der internationalen Kosovo Force (KFOR) im Kosovo verlängert wird. Bei dem Einsatz handelt es sich um die Unterstützung deutscher Streitkräfte an der Entwicklung eines "stabilen, demokratischen, multiethnischen und friedlichen Kosovos".</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die Fraktionen von FDP und Grünen. Damit wurde der Antrag angenommen. AfD und Linke votierten jeweils geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
    ],
    "topic_ids_of_latest_committee": [],
}

politician_route_modified_votes_end_parameter = {
    "id": 78973,
    "label": "Karin Strenz",
    "party": {
        "id": 2,
        "label": "CDU",
        "party_style": {
            "id": 2,
            "display_name": "CDU",
            "foreground_color": "#FFFFFF",
            "background_color": "#636363",
            "border_color": None,
        },
    },
    "occupations": ["MdB"],
    "sidejobs": [
        {
            "id": 6893,
            "entity_type": "sidejob",
            "label": "Vorsitzende",
            "income_level": None,
            "interval": None,
            "created": "2018-04-16",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 4541,
            "entity_type": "sidejob",
            "label": "Stellv. Vorsitzende, ehrenamtlich",
            "income_level": None,
            "interval": None,
            "created": "2017-09-23",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 413,
            "entity_type": "sidejob",
            "label": "Beteiligung (bis 31.12.2014)",
            "income_level": None,
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 872,
                "entity_type": "sidejob_organization",
                "label": "Karin Strenz GbR",
            },
        },
        {
            "id": 412,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
        {
            "id": 411,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
    ],
    "cvs": [
        {
            "id": 633,
            "short_description": "Geboren am 14. Oktober 1967 in Lübz; evangelisch-lutherisch; verheiratet.",
            "raw_text": "Besuch der Polytechnischen Oberschule Lübz; Studium am Institut für Lehrerbildung in Rostock; Studium an der Pädagogischen Hochschule in Magdeburg; Abschluss als Diplom-Lehrerin für Sonderschulen; Zusatzstudium der Erziehungswissenschaften an der Goethe-Universität Frankfurt/Main. Lehrerin an der Sonderschule in Wanzleben bei Magdeburg; 1992 bis 2002 Angestellte einer Import- und Großhandelsfirma in Frankfurt/Main. Seit 2015 Vorsitzende der Deutsch-Kasachischen-Gesellschaft e. V. Seit 2001 Vorsitzende des CDU-Kreisverbandes Parchim; 1999 bis 2005 Mitglied des CDU-Landesvorstandes; 2001 bis 2005 Stellvertretende CDU-Landesvorsitzende; Mitglied der Christlich-Demokratische Arbeitnehmerschaft (CDA); seit 2013 Ehrenvorsitzende CDU-Kreisverband Ludwigslust-Parchim. Seit 1999 Mitglied des Kreistages zu Parchim; seit 2001 Vorsitzende der CDU-Kreistagsfraktion Parchim; seit 2002 Mitglied des Landtages von Mecklenburg-Vorpommern; Ausschüsse: Wirtschaft, Arbeit, Bau und Landesentwicklung, Petitionsausschuss; 2002 bis 2006 arbeitsmarktpolitische Sprecherin der CDU-Fraktion; seit November 2007 verantwortlich für das Sorgentelefon der CDU-Fraktion; 2006 bis 2008 Aufsichtsratsvorsitzende des Flughafens Parchim. Mitglied des Deutschen Bundestages seit Oktober 2009. Karin Strenz ist am 21. März 2021 verstorben, Nachfolgerin ist die Abgeordnete Maika Friemann-Jennert, CDU/CSU. ** verstorben ",
            "politician_id": 78973,
        }
    ],
    "abgeordnetenwatch_url": "https://www.abgeordnetenwatch.de/profile/karin-strenz",
    "weblinks": [
        {
            "politician_id": 78973,
            "link": "https://www.wahl.de/politiker/cdu/karin-strenz",
            "id": 44558,
        },
        {"politician_id": 78973, "link": "http://www.strenz.de/", "id": 44559},
        {
            "politician_id": 78973,
            "link": "https://www.wen-waehlen.de/btw09/kandidaten/karin-strenz_10058.html",
            "id": 44560,
        },
        {
            "politician_id": 78973,
            "link": "https://de.wikipedia.org/wiki/Karin_Strenz",
            "id": 44561,
        },
        {
            "politician_id": 78973,
            "link": "https://www.facebook.com/Karin.Strenz",
            "id": 44562,
        },
    ],
    "votes_and_polls": [
        {
            "Vote": {
                "id": 382871,
                "entity_type": "vote",
                "label": "Karin Strenz - Internetportal Indymedia verbieten",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/382871",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 4018,
                "vote": "no",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 4018,
                "label": "Internetportal Indymedia verbieten",
                "field_intro": '<p>Mit ihrem Antrag fordert die AfD-Fraktion das Verbot des Internetportals <em>indymedia</em>. Laut AfD stelle der Verein eine "Bedrohung der öffentlichen Ordnung durch gewaltbereite Linksextremisten" dar.</p>\r\n\r\n<p>Alle Mitglieder der Fraktionen CDU/CSU, SPD, Grüne. Linke und FDP stimmten ausnahmslos für die Beschlussempfehlung des Ausschusses für Inneres und Heimat und somit gegen den Antrag der AfD.</p>\r\n',
                "field_poll_date": "2021-02-25",
                "poll_passed": False,
            },
        },
        {
            "Vote": {
                "id": 373238,
                "entity_type": "vote",
                "label": "Karin Strenz - Weiterführung des Bundeswehreinsatzes im Irak",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/373238",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3948,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3948,
                "label": "Weiterführung des Bundeswehreinsatzes im Irak",
                "field_intro": '<p>Mit dem Weiterführen des bereits laufenden Bundeswehreinsatzes im Irak soll das erneute Erstarken des islamischen Staates verhindert und die Versöhnung der Konfliktparteien Irak und Syrien gefördert werden.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD sowie die Fraktion der FDP stimmten der <a href="https://dip21.bundestag.de/dip21/btd/19/232/1923212.pdf">Beschlussempfehlung</a> des Auswärtigen Ausschusses zu. Der Antrag der Bundesregierung wurde somit angenommen. Die Fraktionen Bündnis 90/DieGrünen, Die LINKE und die AfD stimmten einstimmig gegen den Einsatz. Auch neun SPD-Fraktionsmitglieder, darunter <a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/dirk-heidenblut">Dirk Heidenblut</a> und&nbsp;<a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/cansel-kiziltepe">Cansel Kiziltepe</a> stellten sich gegen den den <a href="https://dip21.bundestag.de/dip21/btd/19/222/1922207.pdf">Antrag</a>. Ebenso <a class="link-profile" href="https://www.abgeordnetenwatch.de/profile/wieland-schinnenburg">Dr. Wieland Schinnenburg</a> als einziges Mitglied der Fraktion FDP.</p>\r\n\r\n<p>&nbsp;</p>\r\n',
                "field_poll_date": "2020-10-29",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 366526,
                "entity_type": "vote",
                "label": "Karin Strenz - Nachtragshaushalt 2020: Corona Konjunktur- und Krisenbewältigungspaket",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/366526",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3749,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3749,
                "label": "Nachtragshaushalt 2020: Corona Konjunktur- und Krisenbewältigungspaket",
                "field_intro": '<p>Mit dem <a href="http://dip21.bundestag.de/dip21/btd/19/200/1920000.pdf">Gesetzesentwurf </a>fordern die Regierungsfraktionen CDU/CSU und SPD die nachträgliche Erhöhung des Haushaltes für das Jahr 2020 auf 509,3 Milliarden Euro (<a href="https://www.abgeordnetenwatch.de/bundestag/19/abstimmungen/bundeshaushalt-2020">vorher 362 Milliarden Euro</a>) von der Bundesregierung. Mit dem Paket sollen die negativen Auswirkungen auf Wirtschaft und Gesellschaft abgefedert werden.</p>\r\n\r\n<p>Die Regierungsfraktionen stimmten geschlossen <strong>für </strong>den zweiten Nachtragshaushalt. <strong>Gegen </strong>den Antrag votierte die FDP- und AfD-Fraktion. Die Grünen- und Linksfraktion <strong>enthielt </strong>sich zum größten Teil ihrer Stimme. Damit wurde der zweite Nachtragshaushalt für das Jahr 2020 <strong>angenommen</strong>.</p>\r\n',
                "field_poll_date": "2020-07-02",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 365258,
                "entity_type": "vote",
                "label": "Karin Strenz - Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/365258",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3714,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3714,
                "label": "Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "field_intro": '<p>Der <a href="https://dip21.bundestag.de/dip21/btd/19/193/1919371.pdf">Gesetzesentwurf </a>der Bundesregierung will die EU-Richtlinie des EU-Parlamentes zur Stärkung der Rechte von Arbeitnehmer:innen aus dem EU-Ausland umsetzen. Mit der Richtlinie sollen unter anderem aus dem EU-Ausland entsandte Arbeitnehmer:innen nicht mehr nur den Anspruch auf den Mindestlohn, sondern auch auf den Tariflohn aus allgemeinverbindlichen Tarifverträgen haben.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten ebenso wie die Grünenfraktion für den Antrag. Dieser wurde damit angenommen. Die AfD stimmte, genau wie die FDP-Fraktion gegen den Antrag. Die Linken-Abgeordneten enthielten sich ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-06-18",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 363840,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/363840",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3710,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3710,
                "label": "Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr am maritimen Teil der friedenssichernden Mission "United Nations Interim Force in Lebanon" (<a href="https://www.bundeswehr.de/de/einsaetze-bundeswehr/die-bundeswehr-im-libanon">UNIFIL</a>) verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an der Überwachung der Seegrenzen des Libanon.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die FDP und die Grünen. Damit wurde der Antrag angenommen. Die AfD-Fraktion und Linke votierten geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 364549,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/364549",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3711,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3711,
                "label": "Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919001.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr an der internationalen Kosovo Force (KFOR) im Kosovo verlängert wird. Bei dem Einsatz handelt es sich um die Unterstützung deutscher Streitkräfte an der Entwicklung eines "stabilen, demokratischen, multiethnischen und friedlichen Kosovos".</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die Fraktionen von FDP und Grünen. Damit wurde der Antrag angenommen. AfD und Linke votierten jeweils geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 362038,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes in Mali (EUTM Mali 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/362038",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3669,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3669,
                "label": "Verlängerung des Bundeswehreinsatzes in Mali (EUTM Mali 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr an der Militärmission <a href="https://eutmmali.eu/">EUTM</a> verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an dem Beitrag der Europäischen Union zur Ausbildung der malischen Streitkräfte.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die FDP-Fraktion. Damit wurde der Antrag angenommen. Die AfD- und Linksfraktion votierte geschlossen gegen den Antrag. Die Grünen enthielten sich zum großen Teil ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-05-29",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 362747,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes in Mali (MINUSMA 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/362747",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3668,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3668,
                "label": "Verlängerung des Bundeswehreinsatzes in Mali (MINUSMA 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass das Bundeswehrmandat für die Beteiligung an der UN-Mission MINUSMA verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung bewaffneter deutscher Streitkräfte an der "Multidimensionalen Integrierten Stabilisierungsmission der Vereinten Nationen in Mali (MINUSMA)".</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die Grüne- und FDP-Fraktion. Damit wurde der Antrag angenommen. Die AfD- und Linksfraktion votierte geschlossen gegen den Antrag. Bei den Grünen kam es zu fünf Enthaltungen und drei Nein-Stimmen.</p>\r\n',
                "field_poll_date": "2020-05-29",
                "poll_passed": True,
            },
        },
    ],
    "topic_ids_of_latest_committee": [],
}

politician_route_modified_all_parameters = {
    "id": 78973,
    "label": "Karin Strenz",
    "party": {
        "id": 2,
        "label": "CDU",
        "party_style": {
            "id": 2,
            "display_name": "CDU",
            "foreground_color": "#FFFFFF",
            "background_color": "#636363",
            "border_color": None,
        },
    },
    "occupations": ["MdB"],
    "sidejobs": [
        {
            "id": 6893,
            "entity_type": "sidejob",
            "label": "Vorsitzende",
            "income_level": None,
            "interval": None,
            "created": "2018-04-16",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 4541,
            "entity_type": "sidejob",
            "label": "Stellv. Vorsitzende, ehrenamtlich",
            "income_level": None,
            "interval": None,
            "created": "2017-09-23",
            "sidejob_organization": {
                "id": 914,
                "entity_type": "sidejob_organization",
                "label": "Deutsch-Kasachische Gesellschaft e.V.",
            },
        },
        {
            "id": 413,
            "entity_type": "sidejob",
            "label": "Beteiligung (bis 31.12.2014)",
            "income_level": None,
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 872,
                "entity_type": "sidejob_organization",
                "label": "Karin Strenz GbR",
            },
        },
        {
            "id": 412,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
        {
            "id": 411,
            "entity_type": "sidejob",
            "label": "Beratung - Line M-Trade GmbH, Nürnberg (bis Ende Januar 2015)",
            "income_level": "7.000 € bis 15.000 €",
            "interval": None,
            "created": "2017-05-23",
            "sidejob_organization": {
                "id": 3183,
                "entity_type": "sidejob_organization",
                "label": "Beratung - selbständig",
            },
        },
    ],
    "cvs": [
        {
            "id": 633,
            "short_description": "Geboren am 14. Oktober 1967 in Lübz; evangelisch-lutherisch; verheiratet.",
            "raw_text": "Besuch der Polytechnischen Oberschule Lübz; Studium am Institut für Lehrerbildung in Rostock; Studium an der Pädagogischen Hochschule in Magdeburg; Abschluss als Diplom-Lehrerin für Sonderschulen; Zusatzstudium der Erziehungswissenschaften an der Goethe-Universität Frankfurt/Main. Lehrerin an der Sonderschule in Wanzleben bei Magdeburg; 1992 bis 2002 Angestellte einer Import- und Großhandelsfirma in Frankfurt/Main. Seit 2015 Vorsitzende der Deutsch-Kasachischen-Gesellschaft e. V. Seit 2001 Vorsitzende des CDU-Kreisverbandes Parchim; 1999 bis 2005 Mitglied des CDU-Landesvorstandes; 2001 bis 2005 Stellvertretende CDU-Landesvorsitzende; Mitglied der Christlich-Demokratische Arbeitnehmerschaft (CDA); seit 2013 Ehrenvorsitzende CDU-Kreisverband Ludwigslust-Parchim. Seit 1999 Mitglied des Kreistages zu Parchim; seit 2001 Vorsitzende der CDU-Kreistagsfraktion Parchim; seit 2002 Mitglied des Landtages von Mecklenburg-Vorpommern; Ausschüsse: Wirtschaft, Arbeit, Bau und Landesentwicklung, Petitionsausschuss; 2002 bis 2006 arbeitsmarktpolitische Sprecherin der CDU-Fraktion; seit November 2007 verantwortlich für das Sorgentelefon der CDU-Fraktion; 2006 bis 2008 Aufsichtsratsvorsitzende des Flughafens Parchim. Mitglied des Deutschen Bundestages seit Oktober 2009. Karin Strenz ist am 21. März 2021 verstorben, Nachfolgerin ist die Abgeordnete Maika Friemann-Jennert, CDU/CSU. ** verstorben ",
            "politician_id": 78973,
        }
    ],
    "abgeordnetenwatch_url": "https://www.abgeordnetenwatch.de/profile/karin-strenz",
    "weblinks": [
        {
            "link": "https://www.wahl.de/politiker/cdu/karin-strenz",
            "id": 44558,
            "politician_id": 78973,
        },
        {"link": "http://www.strenz.de/", "id": 44559, "politician_id": 78973},
        {
            "link": "https://www.wen-waehlen.de/btw09/kandidaten/karin-strenz_10058.html",
            "id": 44560,
            "politician_id": 78973,
        },
        {
            "link": "https://de.wikipedia.org/wiki/Karin_Strenz",
            "id": 44561,
            "politician_id": 78973,
        },
        {
            "link": "https://www.facebook.com/Karin.Strenz",
            "id": 44562,
            "politician_id": 78973,
        },
    ],
    "votes_and_polls": [
        {
            "Vote": {
                "id": 365258,
                "entity_type": "vote",
                "label": "Karin Strenz - Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/365258",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3714,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3714,
                "label": "Umsetzung der EU-Richtlinie: mehr Rechte für Arbeitnehmer:innen aus dem EU-Ausland",
                "field_intro": '<p>Der <a href="https://dip21.bundestag.de/dip21/btd/19/193/1919371.pdf">Gesetzesentwurf </a>der Bundesregierung will die EU-Richtlinie des EU-Parlamentes zur Stärkung der Rechte von Arbeitnehmer:innen aus dem EU-Ausland umsetzen. Mit der Richtlinie sollen unter anderem aus dem EU-Ausland entsandte Arbeitnehmer:innen nicht mehr nur den Anspruch auf den Mindestlohn, sondern auch auf den Tariflohn aus allgemeinverbindlichen Tarifverträgen haben.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten ebenso wie die Grünenfraktion für den Antrag. Dieser wurde damit angenommen. Die AfD stimmte, genau wie die FDP-Fraktion gegen den Antrag. Die Linken-Abgeordneten enthielten sich ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-06-18",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 364549,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/364549",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3711,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3711,
                "label": "Verlängerung des Bundeswehreinsatzes im Kosovo (KFOR 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919001.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr an der internationalen Kosovo Force (KFOR) im Kosovo verlängert wird. Bei dem Einsatz handelt es sich um die Unterstützung deutscher Streitkräfte an der Entwicklung eines "stabilen, demokratischen, multiethnischen und friedlichen Kosovos".</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die Fraktionen von FDP und Grünen. Damit wurde der Antrag angenommen. AfD und Linke votierten jeweils geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 363840,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/363840",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3710,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3710,
                "label": "Verlängerung des Bundeswehreinsatzes vor der libanesischen Küste (UNIFIL 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919003.pdfhttps://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr am maritimen Teil der friedenssichernden Mission "United Nations Interim Force in Lebanon" (<a href="https://www.bundeswehr.de/de/einsaetze-bundeswehr/die-bundeswehr-im-libanon">UNIFIL</a>) verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an der Überwachung der Seegrenzen des Libanon.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die FDP und die Grünen. Damit wurde der Antrag angenommen. Die AfD-Fraktion und Linke votierten geschlossen gegen den Antrag.</p>\r\n',
                "field_poll_date": "2020-06-17",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 362038,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes in Mali (EUTM Mali 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/362038",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3669,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3669,
                "label": "Verlängerung des Bundeswehreinsatzes in Mali (EUTM Mali 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass die Beteiligung der Bundeswehr an der Militärmission <a href="https://eutmmali.eu/">EUTM</a> verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an dem Beitrag der Europäischen Union zur Ausbildung der malischen Streitkräfte.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die FDP-Fraktion. Damit wurde der Antrag angenommen. Die AfD- und Linksfraktion votierte geschlossen gegen den Antrag. Die Grünen enthielten sich zum großen Teil ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-05-29",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 362747,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes in Mali (MINUSMA 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/362747",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3668,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3668,
                "label": "Verlängerung des Bundeswehreinsatzes in Mali (MINUSMA 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/190/1919002.pdf">Antrag </a>sieht vor, dass das Bundeswehrmandat für die Beteiligung an der UN-Mission MINUSMA verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung bewaffneter deutscher Streitkräfte an der "Multidimensionalen Integrierten Stabilisierungsmission der Vereinten Nationen in Mali (MINUSMA)".</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten der Verlängerung ebenso zu wie die Grüne- und FDP-Fraktion. Damit wurde der Antrag angenommen. Die AfD- und Linksfraktion votierte geschlossen gegen den Antrag. Bei den Grünen kam es zu fünf Enthaltungen und drei Nein-Stimmen.</p>\r\n',
                "field_poll_date": "2020-05-29",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 361329,
                "entity_type": "vote",
                "label": "Karin Strenz - Verlängerung des Bundeswehreinsatzes in Somalia (Atalanta 2020/2021)",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/361329",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3667,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3667,
                "label": "Verlängerung des Bundeswehreinsatzes in Somalia (Atalanta 2020/2021)",
                "field_intro": '<p>Der von der Bundesregierung eingebrachte <a href="https://dip21.bundestag.de/dip21/btd/19/188/1918866.pdf">Antrag </a>sieht vor, dass die Operation <a href="https://eunavfor.eu/">ATALANTA</a>, an der sich die Bundeswehr beteiligt, verlängert wird. Bei dem Einsatz handelt es sich um die Beteiligung deutscher Streitkräfte an einer maritimen Operation der EU, vor der Küste Somalias, mit der Aufgabe, die Piraterie zu bekämpfen und die Gebiete zu überwachen. Abgestimmt wurde über die <a href="https://dip21.bundestag.de/dip21/btd/19/191/1919196.pdf">Beschlussempfehlung </a>des federführenden<a href="https://www.abgeordnetenwatch.de/bundestag/19/ausschuesse/auswaertiger-ausschuss"> Auswärtigen Ausschusses</a>.</p>\r\n\r\n<p>Die Regierungsfraktionen CDU/CSU und SPD stimmten dem Antrag ebenso zu wie die Fraktionen AfD und FDP. Damit wurde der Antrag angenommen. Die Linksfraktion votierte geschlossen gegen den Antrag. Bei den Grünen gab es Zustimmungen und einige Nein-Stimmen, die Hälfte der Fraktion enthielt sich.</p>\r\n',
                "field_poll_date": "2020-05-27",
                "poll_passed": True,
            },
        },
        {
            "Vote": {
                "id": 351737,
                "entity_type": "vote",
                "label": "Karin Strenz - Aufnahme besonders schutzbedürftiger Geflüchteter aus den griechischen Lagern",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/351737",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 3558,
                "vote": "no",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 3558,
                "label": "Aufnahme besonders schutzbedürftiger Geflüchteter aus den griechischen Lagern",
                "field_intro": '<p>Der von der Grünenfraktion eingebrachte <a href="http://dip21.bundestag.de/dip21/btd/19/168/1916838.pdf">Entschließungsantrag </a>fordert die Bundesregierung auf, 5000 besonders schutzbedürftige Menschen aus den Lagern für Geflüchtete auf den griechischen Inseln aufzunehmen.</p>\r\n\r\n<p>Mit 494 Nein-Stimmen der Regierungsfraktionen, der AfD und der FDP wurde der Antrag <strong>abgelehnt</strong>. Neben den Grünen hatte auch die Linksfraktion für den Antrag gestimmt.</p>\r\n',
                "field_poll_date": "2020-03-04",
                "poll_passed": False,
            },
        },
        {
            "Vote": {
                "id": 354937,
                "entity_type": "vote",
                "label": "Karin Strenz - EU-Freisetzungsrichtlinie von genetisch veränderten Organismen stärken",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/354937",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 1762,
                "vote": "no",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 1762,
                "label": "EU-Freisetzungsrichtlinie von genetisch veränderten Organismen stärken",
                "field_intro": '<p>Der <a href="http://dip21.bundestag.de/dip21/btd/19/099/1909952.pdf">Entschließungsantrag </a>der Fraktion Bündnis 90/Die Grünen fordert die Bundesregierung auf, sich auf EU-Ebene dafür einzusetzen, dass bei neuen gentechnischen Methoden weiter nach dem Vorsorgeprinzip schon vor der Nutzung Risiken erkannt und bewertet werden.</p>\r\n\r\n<p>Zu dem Antrag liegt eine <a href="http://dip21.bundestag.de/dip21/btd/19/111/1911179.pdf">Beschlussempfehlung </a>vor, über die namentlich abgestimmt wurde. Mit den Nein-Stimmen der Regierungsfraktionen sowie der FDP-Fraktion wurde der Antrag <strong>abgelehnt</strong>. Neben den grünen Abgeordneten stimmten auch die Abgeordneten der Linksfraktion für den Antrag. Die AfD-Abgeordneten enthielten sich ihrer Stimme.</p>\r\n',
                "field_poll_date": "2020-01-17",
                "poll_passed": False,
            },
        },
        {
            "Vote": {
                "id": 344808,
                "entity_type": "vote",
                "label": "Karin Strenz - Organspenden-Reform: Widerspruchslösung",
                "api_url": "https://www.abgeordnetenwatch.de/api/v2/votes/344808",
                "mandate_id": 45423,
                "fraction_id": 81,
                "poll_id": 1758,
                "vote": "yes",
                "reason_no_show": None,
                "reason_no_show_other": None,
            },
            "Poll": {
                "id": 1758,
                "label": "Organspenden-Reform: Widerspruchslösung",
                "field_intro": '<p>\r\n\tDer Bundestag stimmt über zwei überfraktionell eingebrachte Gesetzesentwürfe ab, welche die Bundesregierung auffordern, dass Organspendemodell in Deutschland zu reformieren. Die Abgeordneten entscheiden über die Einführung einer <a class="read-more" href="http://dip21.bundestag.de/dip21/btd/19/110/1911096.pdf">Widerspruchslösung</a> oder einer <a class="read-more" href="http://dip21.bundestag.de/dip21/btd/19/110/1911087.pdf">Zustimmungslösung</a>.\r\n</p>\r\n\r\n<p>\r\n\tÜber die Widerspruchs- und die Zustimmungslösung sowie über einen AfD-Antrag wurde jeweils namentlich abgestimmt. Hier finden Sie die Ergebnisse zur Widerspruchslösung.\r\n</p>\r\n\r\n<p>\r\n\tMit 292 Ja-Stimmen und 379 Nein-Stimmen wurde der Antrag zur Widerspruchslösung bei 3 Enthaltungen <strong>abgelehnt</strong>. Die Abstimmungsergebnisse zur angenommen Zustimmungslösung finden Sie <a class="link-poll" href="https://www.abgeordnetenwatch.de/bundestag/abstimmungen/organspenden-reform-zustimmungsloesung">hier</a>.\r\n</p>\r\n',
                "field_poll_date": "2020-01-16",
                "poll_passed": False,
            },
        },
    ],
    "topic_ids_of_latest_committee": [],
}
