on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - run: poetry install

      - name: Lint
        run: poetry run python -m black --check .

      # - name: Tests
      #   run: poetry run pytest

  cd:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Face-The-Facts Backend
          environment_name: Face-The-Facts-Backend-Main
          version_label: 12345
          use_existing_version_if_available: true
          region: eu-central-1
          deployment_package: deploy.zip
