on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - run: poetry install

      - name: Lint
        run: poetry run python -m black --check .

      - name: Tests
        run: poetry run pytest

  cd:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: podman build -t backend .
